### ISSUE TITLE
Run livestub server from openapi spec json file

### ISSUE THREAD

**Issue by ekrylovich** [softwaremill/livestub#454]
I'm trying to run livestub server from openapi file by using command:
coursier launch com.softwaremill.sttp.livestub:livestub-app_2.13:0.2.1 -- -p 7070 --openapi-spec openApi.json

I'm receiving error:
`java.lang.RuntimeException: DecodingFailure(Missing required field, List(DownField(version), DownField(info)))
	at sttp.livestub.app.LiveStubLauncher$.$anonfun$main$1(LiveStubLauncher.scala:33)
	at sttp.livestub.app.LiveStubLauncher$.$anonfun$main$1$adapted(LiveStubLauncher.scala:29)
	at cats.SemigroupalArityFunctions.$anonfun$map4$1(SemigroupalArityFunctions.scala:60)
	at cats.data.Validated.ap(Validated.scala:522)
	at cats.data.ValidatedApplicative.ap(Validated.scala:1082)
	at cats.data.ValidatedApplicative.ap(Validated.scala:1075)
	at cats.ComposedApply.$anonfun$ap$2(Composed.scala:54)
	at cats.instances.Function0Instances$$anon$4.$anonfun$ap$1(function.scala:105)
	at com.monovore.decline.Parser.evalResult(Parser.scala:30)
	at com.monovore.decline.Parser.consumeAll(Parser.scala:116)
	at com.monovore.decline.Parser.apply(Parser.scala:19)
	at com.monovore.decline.Command.parse(opts.scala:20)
	at com.monovore.decline.effect.CommandIOApp$.$anonfun$run$4(CommandIOApp.scala:45)
	at use @ sttp.livestub.app.LiveStubLauncher$.$anonfun$main$1(LiveStubLauncher.scala:39)
	at map @ com.monovore.decline.effect.CommandIOApp$.$anonfun$run$7(CommandIOApp.scala:48)
	at delay @ com.monovore.decline.effect.CommandIOApp$.run(CommandIOApp.scala:43)
	at flatMap @ com.monovore.decline.effect.CommandIOApp$.run(CommandIOApp.scala:42)
Caused by: DecodingFailure(Missing required field, List(DownField(version), DownField(info)))`

What i'm doing wrong?

**Comment by ghostbuster91** [comment]
hi, 

It seems that you are missing `info.version` field in your openApi.json which is required according to the specification: https://swagger.io/specification/
